#' Estimates running speed from Arduino Lizards log
#'
#' Reads running speed logs generated by Tomas Fryza's Arduino Lizards software
#' developed for a custom racetrack for sand lizards. Returns top speed in meters per
#' second.
#'
#' @param inputFolder character path to a folder with running log files.
#' @param outputFile character specifying filename where to save the results.
#' @details The function calculates maximum speed the animal achieved between consecutive 
#'    sensors on the racetrack in meters per second. Saves the results into a specified 
#'    file. 
#'
#'    If any experiments did not have two consecutive measurements on neighbouring
#'    sensors, the experiments are considered to have failed. The function issues a warning
#'    and all failed experiments are returned in a file "neuspesneExperimenty.txt" in the
#'    working directory.
#' @note TO DO: incorporate attempt to correct the results, i.e. if speed is negative,
#'    the animal likely ran twice in one measurement.
#' @return Invisibly returns data.frame with animal ID, animal temperature during 
#'    measurement, maximum speed between consecutive sensors in meters per second,
#'    day, month, year of the measurement and the air humidity and temperature of the 
#'    racetrack.  
#' @export

calculateSpeed <- function(inputFolder, outputFile = "runSpeeds.txt"){
	subory = dir(inputFolder, recursive = TRUE, full.names = TRUE)
	
	# extract date from log file header
	datum = as.numeric(unlist(strsplit(unlist(strsplit(readLines(subory[1], n = 1), " "))[4], "\\.")))
	
	# calculate top speed in meters per second
	dat = read.table(subory[1], skip = 5, header = TRUE, sep = ";", na.strings = c("NA", "-"))
	
	rychlost = 100 / suppressWarnings(apply(dat[,2:12], 1, FUN = \(x) min(diff(x), na.rm = T)))
	
	res = data.frame(id.animal = dat$idAnimal, 
					 temp = dat$tempAnimal,
					 speed = rychlost,
					 day = datum[3],
					 month = datum[2],
					 year = datum[1],
					 humidity = dat$humid,
					 air.temp = dat$temp,
					 id.experiment = dat$id)
	neuspesne = data.frame(matrix(NA, ncol = ncol(res), nrow = 1, 
								  dimnames = list(NULL, colnames(res))))
	if(sum(rychlost <= 0) > 0){
		neuspesne = rbind(neuspesne, res[rychlost <= 0, ])
		res = res[rychlost > 0, ]
	}
	
	if(length(subory) > 1) { for(i in 2:length(subory)) {
		# extract date from log file header
		datum = as.numeric(unlist(strsplit(unlist(strsplit(readLines(subory[i], n = 1), " "))[4], "\\.")))
	
		# calculate top speed in meters per second
		dat = read.table(subory[i], skip = 5, header = TRUE, sep = ";", na.strings = c("NA", "-"))
	
		rychlost = 100 / apply(dat[,2:12], 1, FUN = \(x) min(diff(x), na.rm = T))
		
		res2 = data.frame(id.animal = dat$idAnimal, 
					 temp = dat$tempAnimal,
					 speed = rychlost,
					 day = datum[3],
					 month = datum[2],
					 year = datum[1],
					 humidity = dat$humid,
					 air.temp = dat$temp,
					 id.experiment = dat$id)
		if(sum(rychlost <= 0) > 0){
			neuspesne = rbind(neuspesne, res2[rychlost == 0, ])
			res2 = res2[rychlost > 0, ]
		}
		res = rbind(res, res2)
		

	}}
	
	write.table(res, file = outputFile, sep = "\t", row.names = FALSE, quote = FALSE)
	if(nrow(neuspesne) > 1){
		warning("Najdenych ", nrow(neuspesne)-1, " neuspesnych experimentov. Ich zoznam ukladam do suboru 'neuspesneExperimenty.txt'.")
		write.table(neuspesne[-1, ], file = "neuspesneExperimenty.txt", sep = "\t", 
					row.names = FALSE, quote = FALSE)
	}
	return(invisible(res))
}